#! /bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
NO_COLOUR='\033[0m' # No Color
DOWN="false"

while true; do
  result=$(curl -s -o /dev/null -I -w "%{http_code}" "$1")
  if [ $result -eq 200 ];
  then
    if [ $DOWN == "true" ];
    then
      echo -e "\n${GREEN} `date` - $result"
      DOWN="false"
    else
      printf "${GREEN}."
    fi
  else
    if [ $DOWN == "false" ];
    then
      echo -e "\n${RED} `date` - $result"
      DOWN="true"
    else
      printf "${RED}."
    fi
  fi
done
