#! /bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

while true; do
  result=$(wget --spider -S "$1" 2>&1 | grep "HTTP/" | awk '{print $2}')
  if [ $result -eq 200 ]
  then
    printf "${GREEN}."
  else
    echo -e "\n${RED} `date` - $result"
  fi
done
